server:
  port: 7778
  servlet:
    context-path: /payment

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: payment
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

management:
  server:
    port: 17778
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true